### ISSUE TITLE
您好，为什么一直出现net error

### ISSUE THREAD

**Issue by crssbl** [TimeTrapzz/zotero-ccf-info#11]
![image](https://github.com/user-attachments/assets/72dc2f53-4c57-421c-afe6-7112cd0e4931)

**Comment by TimeTrapzz** [comment]
由于dblp官方接口存在一定的限制，在最近的0.2.0版本，我们将ccf信息接口从dblp官方接口切换为自建接口。若显示Net Error，请检查与https://dblp.timetrap.workers.dev/ 的连通性，或考虑降级到0.1.3版本

**Comment by aweng126** [comment]
是不是可以利用本身已经同步得到的【出版会议信息】来和本地构建的ccf列表进行匹配，这样就可以避免和dblp进行通信。定期更新ccf列表元信息就行。

**Comment by TimeTrapzz** [comment]
目前的实现已经不再请求dblp接口，而是自建数据库并通过cloudflare worker进行请求，如果出现网络问题请检查cloudflare的连通性

**Comment by OrenNeko** [comment]
您好，请问目前0.3.1版本的接口已经替换成自建接口了吗？有个使用体验不佳的问题：文献批量生成CCF数据的时候，如果出现访问错误，会导致前面的信息全部变成Net Error。另外想问下自建接口的访问频率限制是多少？如果达到上限了多久后可以恢复使用呢？

**Comment by TimeTrapzz** [comment]
> 您好，请问目前0.3.1版本的接口已经替换成自建接口了吗？有个使用体验不佳的问题：文献批量生成CCF数据的时候，如果出现访问错误，会导致前面的信息全部变成Net Error。另外想问下自建接口的访问频率限制是多少？如果达到上限了多久后可以恢复使用呢？

1. 在很早期的版本ccf评级信息就已替换为自建接口，引用数非自建接口，后者可能存在速率限制，前者走cloudflare可能会有网络问题
2. 你提到的bug在先前版本是没有的吗，近期我只更新了数据的存储和读取逻辑，如果有问题的话可能需要再看看
