### ISSUE TITLE
[Bug report] 插件导致所有文献条目不显示

### ISSUE THREAD

**Issue by JK1Zhang** [TimeTrapzz/zotero-ccf-info#14]
问题描述：点击回收站，回收站不显示条目，此时查看其他条目均不显示。参照[此链接](https://forums.zotero.org/discussion/118699/zotero%E6%89%80%E5%AD%98%E6%96%87%E7%8C%AE%E6%B6%88%E5%A4%B1)，禁用本插件则无该错误。

**Comment by TimeTrapzz** [comment]
你好，我无法复现该问题，或许本插件与其他插件产生了冲突？建议开启本插件，再依次打开其他插件排查一下

**Comment by JK1Zhang** [comment]
你好，我在两台设备上进行了测试，均出现此情况，其中一台不存在其他插件，另一台则保证其他插件都是关闭的，因此可能并非插件冲突导致的。
我做了一些尝试，发现只有在回收站存在被删除的”分类“条目的情况下才会触发此问题。您也许可以尝试新建分类后删除它，再查看回收站，也许可以复现此问题。

**Comment by TimeTrapzz** [comment]
谢谢你的反馈，我已经复现出该问题。但近期可能没有时间修复，我会尽可能找时间修复该问题
