### ISSUE TITLE
Show null for all info

### ISSUE THREAD

**Issue by JK1Zhang** [TimeTrapzz/zotero-ccf-info#6]
Hello. Thank you for contributing the plugin!
After I installed the plugin, all the information was null. Do I need to do anything extra to make this work?
![image](https://github.com/user-attachments/assets/044d83ab-4067-41df-9ed2-1a0cb73ecdfe)

**Comment by TimeTrapzz** [comment]
Hello! You can obtain information by selecting one or more entries and right-clicking on "Get CCF Info".

**Comment by JK1Zhang** [comment]
Thanks. The plugin helps a lot.
